// Curated OSM tag key/value taxonomy for the OSM Downloader
// Keys are the most commonly used primary tags; values are the most common values per key.

export interface OsmTagValue {
  value: string
  label: string
}

export interface OsmTagKey {
  key: string
  label: string
  values: OsmTagValue[]
}

export const OSM_TAGS: OsmTagKey[] = [
  {
    key: 'amenity',
    label: 'Amenity',
    values: [
      // Food & Drink
      { value: 'restaurant',      label: 'Restaurant' },
      { value: 'cafe',            label: 'Cafe' },
      { value: 'fast_food',       label: 'Fast Food' },
      { value: 'bar',             label: 'Bar' },
      { value: 'pub',             label: 'Pub' },
      { value: 'food_court',      label: 'Food Court' },
      { value: 'ice_cream',       label: 'Ice Cream' },
      // Health
      { value: 'hospital',        label: 'Hospital' },
      { value: 'clinic',          label: 'Clinic' },
      { value: 'pharmacy',        label: 'Pharmacy' },
      { value: 'doctors',         label: "Doctor's Surgery" },
      { value: 'dentist',         label: 'Dentist' },
      { value: 'veterinary',      label: 'Veterinary' },
      // Education
      { value: 'school',          label: 'School' },
      { value: 'kindergarten',    label: 'Kindergarten' },
      { value: 'university',      label: 'University' },
      { value: 'college',         label: 'College' },
      { value: 'library',         label: 'Library' },
      // Finance
      { value: 'bank',            label: 'Bank' },
      { value: 'atm',             label: 'ATM' },
      // Transport
      { value: 'parking',         label: 'Parking' },
      { value: 'fuel',            label: 'Fuel Station' },
      { value: 'bus_station',     label: 'Bus Station' },
      { value: 'taxi',            label: 'Taxi' },
      { value: 'charging_station',label: 'EV Charging' },
      { value: 'bicycle_parking', label: 'Bicycle Parking' },
      // Public Services
      { value: 'police',          label: 'Police' },
      { value: 'fire_station',    label: 'Fire Station' },
      { value: 'post_office',     label: 'Post Office' },
      { value: 'post_box',        label: 'Post Box' },
      { value: 'townhall',        label: 'Town Hall' },
      { value: 'courthouse',      label: 'Courthouse' },
      { value: 'embassy',         label: 'Embassy' },
      // Entertainment
      { value: 'cinema',          label: 'Cinema' },
      { value: 'theatre',         label: 'Theatre' },
      { value: 'nightclub',       label: 'Nightclub' },
      { value: 'casino',          label: 'Casino' },
      // Other
      { value: 'place_of_worship',label: 'Place of Worship' },
      { value: 'toilets',         label: 'Toilets' },
      { value: 'community_centre',label: 'Community Centre' },
      { value: 'social_centre',   label: 'Social Centre' },
      { value: 'recycling',       label: 'Recycling' },
      { value: 'shelter',         label: 'Shelter' },
      { value: 'drinking_water',  label: 'Drinking Water' },
      { value: 'marketplace',     label: 'Marketplace' },
    ],
  },
  {
    key: 'shop',
    label: 'Shop',
    values: [
      { value: 'supermarket',     label: 'Supermarket' },
      { value: 'convenience',     label: 'Convenience' },
      { value: 'grocery',         label: 'Grocery' },
      { value: 'bakery',          label: 'Bakery' },
      { value: 'butcher',         label: 'Butcher' },
      { value: 'seafood',         label: 'Seafood' },
      { value: 'deli',            label: 'Deli' },
      { value: 'chemist',         label: 'Chemist' },
      { value: 'clothes',         label: 'Clothes' },
      { value: 'shoes',           label: 'Shoes' },
      { value: 'electronics',     label: 'Electronics' },
      { value: 'computer',        label: 'Computer' },
      { value: 'mobile_phone',    label: 'Mobile Phone' },
      { value: 'furniture',       label: 'Furniture' },
      { value: 'hardware',        label: 'Hardware' },
      { value: 'florist',         label: 'Florist' },
      { value: 'hairdresser',     label: 'Hairdresser' },
      { value: 'beauty',          label: 'Beauty' },
      { value: 'car',             label: 'Car Dealership' },
      { value: 'car_parts',       label: 'Car Parts' },
      { value: 'bicycle',         label: 'Bicycle' },
      { value: 'sports',          label: 'Sports' },
      { value: 'books',           label: 'Books' },
      { value: 'pet',             label: 'Pet' },
      { value: 'toys',            label: 'Toys' },
      { value: 'jewellery',       label: 'Jewellery' },
      { value: 'optician',        label: 'Optician' },
      { value: 'laundry',         label: 'Laundry' },
      { value: 'dry_cleaning',    label: 'Dry Cleaning' },
      { value: 'mall',            label: 'Shopping Mall' },
      { value: 'department_store',label: 'Department Store' },
    ],
  },
  {
    key: 'tourism',
    label: 'Tourism',
    values: [
      { value: 'hotel',           label: 'Hotel' },
      { value: 'motel',           label: 'Motel' },
      { value: 'hostel',          label: 'Hostel' },
      { value: 'guest_house',     label: 'Guest House' },
      { value: 'camp_site',       label: 'Camp Site' },
      { value: 'caravan_site',    label: 'Caravan Site' },
      { value: 'attraction',      label: 'Attraction' },
      { value: 'museum',          label: 'Museum' },
      { value: 'gallery',         label: 'Gallery' },
      { value: 'zoo',             label: 'Zoo' },
      { value: 'aquarium',        label: 'Aquarium' },
      { value: 'theme_park',      label: 'Theme Park' },
      { value: 'viewpoint',       label: 'Viewpoint' },
      { value: 'information',     label: 'Information' },
      { value: 'picnic_site',     label: 'Picnic Site' },
    ],
  },
  {
    key: 'leisure',
    label: 'Leisure',
    values: [
      { value: 'park',            label: 'Park' },
      { value: 'garden',          label: 'Garden' },
      { value: 'playground',      label: 'Playground' },
      { value: 'sports_centre',   label: 'Sports Centre' },
      { value: 'fitness_centre',  label: 'Fitness Centre / Gym' },
      { value: 'stadium',         label: 'Stadium' },
      { value: 'pitch',           label: 'Sports Pitch' },
      { value: 'track',           label: 'Running / Cycling Track' },
      { value: 'swimming_pool',   label: 'Swimming Pool' },
      { value: 'golf_course',     label: 'Golf Course' },
      { value: 'marina',          label: 'Marina' },
      { value: 'nature_reserve',  label: 'Nature Reserve' },
      { value: 'dog_park',        label: 'Dog Park' },
      { value: 'skate_park',      label: 'Skate Park' },
      { value: 'miniature_golf',  label: 'Miniature Golf' },
      { value: 'bowling_alley',   label: 'Bowling Alley' },
      { value: 'beach_resort',    label: 'Beach Resort' },
    ],
  },
  {
    key: 'highway',
    label: 'Highway / Path',
    values: [
      { value: 'motorway',        label: 'Motorway' },
      { value: 'trunk',           label: 'Trunk Road' },
      { value: 'primary',         label: 'Primary Road' },
      { value: 'secondary',       label: 'Secondary Road' },
      { value: 'tertiary',        label: 'Tertiary Road' },
      { value: 'residential',     label: 'Residential Road' },
      { value: 'service',         label: 'Service Road' },
      { value: 'footway',         label: 'Footway' },
      { value: 'cycleway',        label: 'Cycleway' },
      { value: 'path',            label: 'Path' },
      { value: 'pedestrian',      label: 'Pedestrian Street' },
      { value: 'steps',           label: 'Steps' },
      { value: 'bus_stop',        label: 'Bus Stop' },
      { value: 'crossing',        label: 'Crossing' },
      { value: 'traffic_signals', label: 'Traffic Signals' },
    ],
  },
  {
    key: 'building',
    label: 'Building',
    values: [
      { value: 'yes',             label: 'Any Building' },
      { value: 'residential',     label: 'Residential' },
      { value: 'apartments',      label: 'Apartments' },
      { value: 'house',           label: 'House' },
      { value: 'commercial',      label: 'Commercial' },
      { value: 'retail',          label: 'Retail' },
      { value: 'industrial',      label: 'Industrial' },
      { value: 'warehouse',       label: 'Warehouse' },
      { value: 'office',          label: 'Office' },
      { value: 'school',          label: 'School' },
      { value: 'hospital',        label: 'Hospital' },
      { value: 'church',          label: 'Church' },
      { value: 'civic',           label: 'Civic' },
      { value: 'stadium',         label: 'Stadium' },
      { value: 'hotel',           label: 'Hotel' },
      { value: 'garage',          label: 'Garage' },
    ],
  },
  {
    key: 'natural',
    label: 'Natural',
    values: [
      { value: 'wood',            label: 'Wood / Forest' },
      { value: 'tree',            label: 'Tree' },
      { value: 'tree_row',        label: 'Tree Row' },
      { value: 'water',           label: 'Water Body' },
      { value: 'wetland',         label: 'Wetland' },
      { value: 'beach',           label: 'Beach' },
      { value: 'cliff',           label: 'Cliff' },
      { value: 'coastline',       label: 'Coastline' },
      { value: 'peak',            label: 'Peak / Summit' },
      { value: 'grassland',       label: 'Grassland' },
      { value: 'heath',           label: 'Heath' },
      { value: 'scrub',           label: 'Scrub' },
      { value: 'sand',            label: 'Sand / Dune' },
      { value: 'cave_entrance',   label: 'Cave Entrance' },
    ],
  },
  {
    key: 'landuse',
    label: 'Land Use',
    values: [
      { value: 'residential',     label: 'Residential' },
      { value: 'commercial',      label: 'Commercial' },
      { value: 'industrial',      label: 'Industrial' },
      { value: 'retail',          label: 'Retail' },
      { value: 'forest',          label: 'Forest' },
      { value: 'farmland',        label: 'Farmland' },
      { value: 'farmyard',        label: 'Farmyard' },
      { value: 'meadow',          label: 'Meadow' },
      { value: 'grass',           label: 'Grass' },
      { value: 'cemetery',        label: 'Cemetery' },
      { value: 'military',        label: 'Military' },
      { value: 'recreation_ground', label: 'Recreation Ground' },
      { value: 'allotments',      label: 'Allotments' },
      { value: 'quarry',          label: 'Quarry' },
      { value: 'brownfield',      label: 'Brownfield' },
      { value: 'greenfield',      label: 'Greenfield' },
    ],
  },
  {
    key: 'office',
    label: 'Office',
    values: [
      { value: 'yes',             label: 'Any Office' },
      { value: 'company',         label: 'Company' },
      { value: 'government',      label: 'Government' },
      { value: 'ngo',             label: 'NGO / Non-profit' },
      { value: 'lawyers',         label: 'Lawyers' },
      { value: 'accountant',      label: 'Accountant' },
      { value: 'estate_agent',    label: 'Estate Agent' },
      { value: 'insurance',       label: 'Insurance' },
      { value: 'it',              label: 'IT' },
      { value: 'financial',       label: 'Financial' },
      { value: 'architect',       label: 'Architect' },
      { value: 'engineer',        label: 'Engineer' },
    ],
  },
  {
    key: 'healthcare',
    label: 'Healthcare',
    values: [
      { value: 'hospital',        label: 'Hospital' },
      { value: 'clinic',          label: 'Clinic' },
      { value: 'doctor',          label: 'Doctor' },
      { value: 'dentist',         label: 'Dentist' },
      { value: 'pharmacy',        label: 'Pharmacy' },
      { value: 'optometrist',     label: 'Optometrist' },
      { value: 'physiotherapist', label: 'Physiotherapist' },
      { value: 'psychotherapist', label: 'Psychotherapist' },
      { value: 'laboratory',      label: 'Laboratory' },
      { value: 'blood_bank',      label: 'Blood Bank' },
      { value: 'rehabilitation',  label: 'Rehabilitation' },
    ],
  },
]
